---
- name: Configure Elk VM with Docker
  hosts: elk
  remote_user: RedAdmin-Elk
  become: true
  tasks:

    - name: Install Docker.io
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present

    - name: Install python-pip
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: Install Docker Python Module
      pip:
        name: docker
        state: present

    - name: Increase the Virtual Memory on the Elk VM
      command: sysctl -w vm.max_map_count=262144


    - name: Use more memory
      sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        reload: yes

    - name: Download and Launch a Docker Elk Container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044
          
    - name: Enable Service Docker on Boot
      systemd:
        name: docker
        enabled: yes
